//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.15 at 09:24:16 PM MSK 
//


package ru.emorozov.springbootapp.soap.post;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.emorozov.springbootapp.soap.post package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.emorozov.springbootapp.soap.post
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostRequest }
     * 
     */
    public PostRequest createPostRequest() {
        return new PostRequest();
    }

    /**
     * Create an instance of {@link PostResponse }
     * 
     */
    public PostResponse createPostResponse() {
        return new PostResponse();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link PingResponse }
     * 
     */
    public PingResponse createPingResponse() {
        return new PingResponse();
    }

    /**
     * Create an instance of {@link CreatePostRequest }
     * 
     */
    public CreatePostRequest createCreatePostRequest() {
        return new CreatePostRequest();
    }

    /**
     * Create an instance of {@link CreatePostResponse }
     * 
     */
    public CreatePostResponse createCreatePostResponse() {
        return new CreatePostResponse();
    }

    /**
     * Create an instance of {@link RemovePostRequest }
     * 
     */
    public RemovePostRequest createRemovePostRequest() {
        return new RemovePostRequest();
    }

    /**
     * Create an instance of {@link RemovePostResponse }
     * 
     */
    public RemovePostResponse createRemovePostResponse() {
        return new RemovePostResponse();
    }

    /**
     * Create an instance of {@link GetPostsRequest }
     * 
     */
    public GetPostsRequest createGetPostsRequest() {
        return new GetPostsRequest();
    }

    /**
     * Create an instance of {@link GetPostsResponse }
     * 
     */
    public GetPostsResponse createGetPostsResponse() {
        return new GetPostsResponse();
    }

    /**
     * Create an instance of {@link PostRecord }
     * 
     */
    public PostRecord createPostRecord() {
        return new PostRecord();
    }

    /**
     * Create an instance of {@link ResultRecord }
     * 
     */
    public ResultRecord createResultRecord() {
        return new ResultRecord();
    }

}
