//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.15 at 09:24:16 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://emorozov.ru/springbootapp/soap/post", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.emorozov.springbootapp.soap.post;
